config/routes.rb
Rails.application.routes.draw do
  resources :reps
  resources :pictures
  resources :images
  resources :useragendas, only: [:attend]

  resources :mobiles do
    collection do
      post 'create_code'
      post 'verify'
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations'}
  devise_scope :user do
    get 'agendas/users/:id', to: 'users/registrations#profile'
    get '/home', to: 'users/registrations#home'
    get '/album', to: 'users/registrations#album'
    get '/info', to: 'users/registrations#info'
    get '/attends', to: 'users/registrations#attends'
    get '/pubs', to: 'users/registrations#pubs'
    get '/settings', to: 'users/registrations#settings'
    get '/info/nick', to: 'users/registrations#nick'
  end

  resource :user, only: [:edit] do
    collection do
      post 'create_code'
      get 'forget_password'
      get 'reset_password'
      patch 'update_password'
      get 'verify_code'
      post 'code_verification'
      post 'verify_phone'
    end
  end

  root 'agendas#index'

  post 'agendas/attend/:id', to: 'useragendas#attend'
  get 'useragendas/select/:id', to: 'useragendas#select'

  resources :agendas do
    resources :messages, except: [:show, :index]
  end

  resources :messages do
    resources :reps, except: [:show, :index]
  end

  resources :zones do  
    resources :agendas
  end

  resources :categories do  
    resources :agendas
  end

  get 'setloc' => "amap#setloc"

  get 'wechat' => "wechats#auth_wechat"
  post 'wechat' => "wechats#process_request"

namespace :api do
  namespace :v1 do
    resources :trainers, only: [:index, :create, :show, :update, :destroy]
    get 'uptoken_gen/index'
  end
end

end

app/models/age.rb
class Age < ActiveRecord::Base
	has_many :users
end

app/models/agenda.rb
class Agenda < ActiveRecord::Base


	has_many :useragendas, dependent: :destroy 
	has_many :users, through: :useragendas
	has_many :images, dependent: :destroy
	has_many :messages, dependent: :destroy
	
    belongs_to :category
    belongs_to :zone
    belongs_to :cost

    validates :name, :category_id, :zone_id, :time, :datatime, presence: true
    validates :userlimit, numericality: {greater_or_equal_than: 1, less_or_equal_than: 100}

    def self.text_search(query)
      if query.present?
      	where("name ilike :q or description ilike :q", q: "%#{query}%")
      else
      	scoped
      end 
    end 
end

app/models/carrer.rb
class Carrer < ActiveRecord::Base
	has_many :users
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :agendas
end

app/models/cost.rb
class Cost < ActiveRecord::Base
	has_many :users
end

app/models/gender.rb
class Gender < ActiveRecord::Base
	has_many :users
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :agenda
end

app/models/message.rb
class Message < ActiveRecord::Base
	validates :comment, presence: true
	belongs_to :agenda
	has_many :reps, dependent: :destroy
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user
end

app/models/rep.rb
class Rep < ActiveRecord::Base
	validates :comment, presence: true
	belongs_to :message
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :icon, UserUploader

  has_many :useragendas
  has_many :agendas, through: :useragendas
  has_many :pictures

  belongs_to :age
  belongs_to :carrer
  belongs_to :gender

  #validates :name, :introduction, :icon, :gender_id, :age_id, :carrer_id, presence: true
  def email_required?
    false
  end
 
  def email_changed?
    false
  end
end

app/models/useragenda.rb
class Useragenda < ActiveRecord::Base
	belongs_to :user
	belongs_to :agenda
end

app/models/zone.rb
class Zone < ActiveRecord::Base
	has_many :agendas
end

app/controllers/useragendas_controller.rb
class UseragendasController < ApplicationController
  before_action :set_useragenda, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :attend]

  # GET /useragendas
  # GET /useragendas.json
  def index
    @useragendas = Useragenda.all
  end

  # GET /useragendas/1
  # GET /useragendas/1.json
  def show
  end

  # GET /useragendas/new
  def new
    @useragenda = Useragenda.new
  end

  # GET /useragendas/1/edit
  def edit
  end

  # POST /useragendas
  # POST /useragendas.json
  def create
    @useragenda = Useragenda.new(useragenda_params)

    respond_to do |format|
      if @useragenda.save
        format.html { redirect_to @useragenda, notice: 'Useragenda was successfully created.' }
        format.json { render :show, status: :created, location: @useragenda }
      else
        format.html { render :new }
        format.json { render json: @useragenda.errors, status: :unprocessable_entity }
      end
    end
  end

# GET /useragendas/attend/1
  def attend
      @agenda = Agenda.find(params[:id])
      if current_user.id==@agenda.sponsor_id
        #redirect_to @agenda, warning: '您是该邀约的发起者!'
        render :text => "您是该邀约的发起者!"
      else  
        if @agenda.isfull==1
          #redirect_to @agenda, warning: '人数已满!'
          render :text => "人数已满!"
        else
          current_user.useragendas.create(user_id:current_user.id, agenda_id:@agenda.id, isselected:0)
          #redirect_to @agenda, notice: '报名成功!'
          render :text => "报名成功!"
        end
      end
  end

  def select
    @agenda = Agenda.find(params[:id])
    
    if(@agenda.isoverdue==0)
      @t=@agenda.time
      @agendammt= @agenda.datatime.to_s+ " " +@t.strftime("%H")+":"+@t.strftime("%M")+":"+@t.strftime("%S")
      if((Time.parse(@agendammt)-Time.now)<=0)
        @agenda.update_attribute(:isoverdue, 1)
      end
    end

    if @agenda.isfull==1 || @agenda.isoverdue==1
      if @agenda.isfull==1
        redirect_to @agenda, warning: '人数已满!'
      else
        redirect_to @agenda, warning: '该邀约已过期!'
      end
    elsif params[:selected_ids]
          params[:selected_ids].each { |selected_id|
            @useragenda = Useragenda.where(user_id: selected_id, agenda_id: @agenda.id)
            @useragenda.update_all(:isselected => 1)
            # the count should exclude sponser itself
            if Useragenda.where(agenda_id:@agenda.id, isselected:1).count >= @agenda.userlimit
              @agenda.update_attribute(:isfull, 1)
              break
            end
          }
          if @agenda.isfull==1
            redirect_to @agenda, notice: 'this agenda attendees is full.'
          else  
            redirect_to @agenda
          end
    else
      redirect_to @agenda, notice: 'plese select person to attend.'
    end
  end

  # PATCH/PUT /useragendas/1
  # PATCH/PUT /useragendas/1.json
  def update
    respond_to do |format|
      if @useragenda.update(useragenda_params)
        format.html { redirect_to @useragenda, notice: 'Useragenda was successfully updated.' }
        format.json { render :show, status: :ok, location: @useragenda }
      else
        format.html { render :edit }
        format.json { render json: @useragenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /useragendas/1
  # DELETE /useragendas/1.json
  def destroy
    @useragenda.destroy
    respond_to do |format|
      format.html { redirect_to useragendas_url, notice: 'Useragenda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_useragenda
      @useragenda = Useragenda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def useragenda_params
      params.require(:useragenda).permit(:user_id, :agenda_id, :agendaFlag, :sponsorFlag)
    end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/amap_helper.rb
module AmapHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/helpers/reps_helper.rb
module RepsHelper
end

app/helpers/useragendas_helper.rb
module UseragendasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/useragendas/_form.html.erb
<%= form_for(@useragenda) do |f| %>
  <% if @useragenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@useragenda.errors.count, "error") %> prohibited this useragenda from being saved:</h2>

      <ul>
      <% @useragenda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :agenda_id %><br>
    <%= f.number_field :agenda_id %>
  </div>
  <div class="field">
    <%= f.label :agendaFlag %><br>
    <%= f.number_field :agendaFlag %>
  </div>
  <div class="field">
    <%= f.label :sponsorFlag %><br>
    <%= f.number_field :sponsorFlag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/useragendas/attend.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Thanks for attending!</strong>
</p>




<%= link_to 'Back', agendas_path %>

app/views/useragendas/edit.html.erb
<h1>Editing Useragenda</h1>

<%= render 'form' %>

<%= link_to 'Show', @useragenda %> |
<%= link_to 'Back', useragendas_path %>

app/views/useragendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Useragendas</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Agenda</th>
      <th>Agendaflag</th>
      <th>Sponsorflag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @useragendas.each do |useragenda| %>
      <tr>
        <td><%= useragenda.user_id %></td>
        <td><%= useragenda.agenda_id %></td>
        <td><%= useragenda.agendaFlag %></td>
        <td><%= useragenda.sponsorFlag %></td>
        <td><%= link_to 'Show', useragenda %></td>
        <td><%= link_to 'Edit', edit_useragenda_path(useragenda) %></td>
        <td><%= link_to 'Destroy', useragenda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Useragenda', new_useragenda_path %>

app/views/useragendas/new.html.erb
<h1>New Useragenda</h1>

<%= render 'form' %>

<%= link_to 'Back', useragendas_path %>

app/views/useragendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @useragenda.user_id %>
</p>

<p>
  <strong>Agenda:</strong>
  <%= @useragenda.agenda_id %>
</p>

<p>
  <strong>Agendaflag:</strong>
  <%= @useragenda.agendaFlag %>
</p>

<p>
  <strong>Sponsorflag:</strong>
  <%= @useragenda.sponsorFlag %>
</p>

<%= link_to 'Edit', edit_useragenda_path(@useragenda) %> |
<%= link_to 'Back', useragendas_path %>