config/routes.rb
Rails.application.routes.draw do
  resources :reps
  resources :pictures
  resources :images
  resources :useragendas, only: [:attend]

  resources :mobiles do
    collection do
      post 'create_code'
      post 'verify'
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations'}
  devise_scope :user do
    get 'agendas/users/:id', to: 'users/registrations#profile'
    get '/home', to: 'users/registrations#home'
    get '/album', to: 'users/registrations#album'
    get '/info', to: 'users/registrations#info'
    get '/attends', to: 'users/registrations#attends'
    get '/pubs', to: 'users/registrations#pubs'
    get '/settings', to: 'users/registrations#settings'
    get '/info/nick', to: 'users/registrations#nick'
  end

  resource :user, only: [:edit] do
    collection do
      post 'create_code'
      get 'forget_password'
      get 'reset_password'
      patch 'update_password'
      get 'verify_code'
      post 'code_verification'
      post 'verify_phone'
    end
  end

  root 'agendas#index'

  post 'agendas/attend/:id', to: 'useragendas#attend'
  get 'useragendas/select/:id', to: 'useragendas#select'

  resources :agendas do
    resources :messages, except: [:show, :index]
  end

  resources :messages do
    resources :reps, except: [:show, :index]
  end

  resources :zones do  
    resources :agendas
  end

  resources :categories do  
    resources :agendas
  end

  get 'setloc' => "amap#setloc"

  get 'wechat' => "wechats#auth_wechat"
  post 'wechat' => "wechats#process_request"

namespace :api do
  namespace :v1 do
    resources :trainers, only: [:index, :create, :show, :update, :destroy]
    get 'uptoken_gen/index'
  end
end

end

app/models/age.rb
class Age < ActiveRecord::Base
	has_many :users
end

app/models/agenda.rb
class Agenda < ActiveRecord::Base


	has_many :useragendas, dependent: :destroy 
	has_many :users, through: :useragendas
	has_many :images, dependent: :destroy
	has_many :messages, dependent: :destroy
	
    belongs_to :category
    belongs_to :zone
    belongs_to :cost

    validates :name, :category_id, :zone_id, :time, :datatime, presence: true
    validates :userlimit, numericality: {greater_or_equal_than: 1, less_or_equal_than: 100}

    def self.text_search(query)
      if query.present?
      	where("name ilike :q or description ilike :q", q: "%#{query}%")
      else
      	scoped
      end 
    end 
end

app/models/carrer.rb
class Carrer < ActiveRecord::Base
	has_many :users
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :agendas
end

app/models/cost.rb
class Cost < ActiveRecord::Base
	has_many :users
end

app/models/gender.rb
class Gender < ActiveRecord::Base
	has_many :users
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :agenda
end

app/models/message.rb
class Message < ActiveRecord::Base
	validates :comment, presence: true
	belongs_to :agenda
	has_many :reps, dependent: :destroy
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user
end

app/models/rep.rb
class Rep < ActiveRecord::Base
	validates :comment, presence: true
	belongs_to :message
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :icon, UserUploader

  has_many :useragendas
  has_many :agendas, through: :useragendas
  has_many :pictures

  belongs_to :age
  belongs_to :carrer
  belongs_to :gender

  #validates :name, :introduction, :icon, :gender_id, :age_id, :carrer_id, presence: true
  def email_required?
    false
  end
 
  def email_changed?
    false
  end
end

app/models/useragenda.rb
class Useragenda < ActiveRecord::Base
	belongs_to :user
	belongs_to :agenda
end

app/models/zone.rb
class Zone < ActiveRecord::Base
	has_many :agendas
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    respond_to do |format|
      if params[:pictures]
          #===== The magic is here ;)
          params[:pictures].each { |picture|
            current_user.pictures.create(picture: picture, user_id: current_user.id)
          }
      end
        format.html { redirect_to "/home", notice: 'picture was successfully created.' }
        format.json { render :show, status: :created, location: "/home" }
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to "/home", notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:user_id, :picture, :pictures)
    end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/amap_helper.rb
module AmapHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/reps_helper.rb
module RepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pictures</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.user_id %></td>
        <td><%= picture.picture %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @picture.user_id %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @picture.picture %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>