config/routes.rb
Rails.application.routes.draw do
  resources :reps
  resources :pictures
  resources :images
  resources :useragendas, only: [:attend]

  resources :mobiles do
    collection do
      post 'create_code'
      post 'verify'
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations'}
  devise_scope :user do
    get 'agendas/users/:id', to: 'users/registrations#profile'
    get '/home', to: 'users/registrations#home'
    get '/album', to: 'users/registrations#album'
    get '/info', to: 'users/registrations#info'
    get '/attends', to: 'users/registrations#attends'
    get '/pubs', to: 'users/registrations#pubs'
    get '/settings', to: 'users/registrations#settings'
    get '/info/nick', to: 'users/registrations#nick'
  end

  resource :user, only: [:edit] do
    collection do
      post 'create_code'
      get 'forget_password'
      get 'reset_password'
      patch 'update_password'
      get 'verify_code'
      post 'code_verification'
      post 'verify_phone'
    end
  end

  root 'agendas#index'

  post 'agendas/attend/:id', to: 'useragendas#attend'
  get 'useragendas/select/:id', to: 'useragendas#select'

  resources :agendas do
    resources :messages, except: [:show, :index]
  end

  resources :messages do
    resources :reps, except: [:show, :index]
  end

  resources :zones do  
    resources :agendas
  end

  resources :categories do  
    resources :agendas
  end

  get 'setloc' => "amap#setloc"

  get 'wechat' => "wechats#auth_wechat"
  post 'wechat' => "wechats#process_request"

namespace :api do
  namespace :v1 do
    resources :trainers, only: [:index, :create, :show, :update, :destroy]
    get 'uptoken_gen/index'
  end
end

end

app/models/age.rb
class Age < ActiveRecord::Base
	has_many :users
end

app/models/agenda.rb
class Agenda < ActiveRecord::Base


	has_many :useragendas, dependent: :destroy 
	has_many :users, through: :useragendas
	has_many :images, dependent: :destroy
	has_many :messages, dependent: :destroy
	
    belongs_to :category
    belongs_to :zone
    belongs_to :cost

    validates :name, :category_id, :zone_id, :time, :datatime, presence: true
    validates :userlimit, numericality: {greater_or_equal_than: 1, less_or_equal_than: 100}

    def self.text_search(query)
      if query.present?
      	where("name ilike :q or description ilike :q", q: "%#{query}%")
      else
      	scoped
      end 
    end 
end

app/models/carrer.rb
class Carrer < ActiveRecord::Base
	has_many :users
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :agendas
end

app/models/cost.rb
class Cost < ActiveRecord::Base
	has_many :users
end

app/models/gender.rb
class Gender < ActiveRecord::Base
	has_many :users
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :agenda
end

app/models/message.rb
class Message < ActiveRecord::Base
	validates :comment, presence: true
	belongs_to :agenda
	has_many :reps, dependent: :destroy
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user
end

app/models/rep.rb
class Rep < ActiveRecord::Base
	validates :comment, presence: true
	belongs_to :message
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :icon, UserUploader

  has_many :useragendas
  has_many :agendas, through: :useragendas
  has_many :pictures

  belongs_to :age
  belongs_to :carrer
  belongs_to :gender

  #validates :name, :introduction, :icon, :gender_id, :age_id, :carrer_id, presence: true
  def email_required?
    false
  end
 
  def email_changed?
    false
  end
end

app/models/useragenda.rb
class Useragenda < ActiveRecord::Base
	belongs_to :user
	belongs_to :agenda
end

app/models/zone.rb
class Zone < ActiveRecord::Base
	has_many :agendas
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    #@agendas = Agenda.where(category_id: @category.id).order("created_at DESC")
      @agendas = @category.agendas
      @categories = Category.all.order(:id);
      @agendas.each do |agenda|
        if(agenda.isoverdue==0)
          @t=agenda.time
          @agendammt= agenda.datatime.to_s+ " " +@t.strftime("%H")+":"+@t.strftime("%M")+":"+@t.strftime("%S")
          if((Time.parse(@agendammt)-Time.now)<=0)
            agenda.update_attribute(:isoverdue, 1)
          end
        end
      end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/amap_helper.rb
module AmapHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/helpers/reps_helper.rb
module RepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/categories/_agdblock.mobile.erb
<% @sponsor=User.find(@agenda.sponsor_id) %>
<% @zone=Zone.find(@agenda.zone_id)%>
<% @category=Category.find(@agenda.category_id)%>
<% @t=@agenda.time %>
<% @time=@t.strftime("%H")+":"+@t.strftime("%M")+":"+@t.strftime("%S") %>
<% @agendammt = @agenda.datatime.to_s+ " " + @time %>
<% @day_delta = ((Time.parse(@agendammt)-(Time.now.at_beginning_of_day+60*60*24))/(60*60*24)) %>
<a href=<%=agenda_path(@agenda.id)%>>
<div class="msgblock z-depth-2">
  <div class="msgblock-up">
    <div class="msgblock-up-left">
      <div id="msgblock-icon">
        <img class="radius-icon" src='<%=@sponsor.icon.thumb.url%>'>
      </div>
    </div>
    <div class="msgblock-up-right">
      <div id="msgblock-up-right-up">
        <h id="agdblock-name">
          <%= @sponsor.name%>
        </h>
        <%if @sponsor.gender!=nil %>
          <% if @sponsor.gender.name == '男' %>
          <!--% if 1 %-->
            <h id="agdblock-userinfo-male">
              <h id='male-icon'>♂</h>
              <h id="age">
                <%if @sponsor.birth!=nil%>
                  <%= Time.now.year-@sponsor.birth.year %>
                <%end%>
              </h>
            </h>
          <% else %>
            <h id="agdblock-userinfo-female">
              <h id='female-icon'>♀</h>
              <h id="age">
                <%if @sponsor.birth!=nil%>
                  <%= Time.now.year-@sponsor.birth.year %>
                <%end%>
              </h>
            </h>
          <% end %>
        <% end %>
        <!--%= @sponsor.age.name %-->
   
        <div class="block-float-right">
          <div class="chip block-chip">
            <%= @zone.name %>
          </div>
          <div class="chip block-chip">
            <%= @category.name %>
          </div>
        </div>
      </div>
      
      <div class="words-trancated" id="msgblock-up-right-down">
      <i class="material-icons left" id="agdblock-icon-flag">&#xE153;</i>
      <div class="block-words" id="agdblock-agdname">
        <%= @agenda.name %>
      </div>
      </div>
    </div>
  </div>

  <div class="msgblock-down">
    <% if @agenda.isoverdue==1%>
      <div class="block-words">
        <i class="material-icons left" id="agdblock-icon-overdue">&#xE857;</i>
        <div id="agdblock-time">
          已过期
        <div class="block-float-right" id=<%="create-time-#{@itemid}-#{@agenda.id}"%>>
          1天前
        </div>
        </div>
      </div>
    <% else %>
      <div class="block-words">
        <i class="material-icons left" id="agdblock-icon-time">&#xE8B5;</i>
          <div id="agdblock-time">
          <% if @day_delta<0 %>
            今天
          <% elsif @day_delta>=0 && @day_delta<1 %>
            明天
          <% elsif @day_delta>=1 && @day_delta<2%>
            后天
          <% else %>
            三天后
          <% end %>
          <%=@t.strftime("%H")+":"+@t.strftime("%M")%>
          <div class="block-float-right" id=<%="create-time-#{@itemid}-#{@agenda.id}"%>>
            1天前
          </div>
          </div>
      </div>
    <% end %>
      <i class="material-icons left" id="agdblock-icon-address">&#xE0C8;</i>
      <div class="block-words" id="agdblock-address">
        <%= @agenda.address %>
      </div>
  </div>
</div>
</a>

<%= javascript_tag do %>
  var createtime = '<%= @agenda.created_at %>';
  var agdid= '<%= @agenda.id %>'
  var itemid= '<%= @itemid%>'
<% end %>

<script type="text/javascript">
  moment.locale('zh-cn');
  var crtime = moment(createtime, "YYYY-MM-DD HH:mm"); 
  var create_time = document.getElementById("create-time-"+itemid+"-"+agdid);
  create_time.innerHTML=crtime.fromNow();
</script>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>类别:</strong>
  <%= @category.name %>
</p>

<div class="row" id="agenda-list">
  <% @agendas.each do |agenda| %>
    <% @images=agenda.images%>
     <% @image=@images.first%>
        <% @sponsor=User.find(agenda.sponsor_id) %>
          <% @zone=Zone.find(agenda.zone_id)%>
          <div class="col s6 m3" id="card-container">
            <div class="card">
              <div class="card-image">
                <%= link_to image_tag(@image.image.thumb.url), agenda %>
              </div>
              <div class="card-content" id="agenda-description">
                 <p align="center">
                    <%= link_to @zone.name, zone_agendas_path(@zone.id) %>
                    <%= link_to @category.name, category_agendas_path(@category.id) %>
                 </p>
                <p>发起者：<%= link_to("#{@sponsor.name}","/agendas/users/#{agenda.sponsor_id}")%></p>
                <p><%=agenda.description%></p>
              </div>
            </div>
          </div>
  <% end %>
</div>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/show.mobile.erb
<% if flash[:notice] %>
  <!--ignore the notice for user sign in, sign out-->
  <% notice %>
<% end %>




<div class="header-wrp">
  <div id="search-wrp-right"> 
  </div>
  <div id="search-wrp-left">
    上海
  </div>
  <div id="search-field">
    <form name="searchform1" method="get" action="/agendas">
      <input type="text" style="border-radius:10px;" name="query" id="s1" class="searchfieldjs" placeholder="搜索邀约..." tabindex="2">
      <!--input type="submit"  id="searchbtn1" value=""-->
      <button type="submit" id="searchbtn1">
        <i class="material-icons left" id="searicon">&#xE8B6;</i>
      </button>
    </form>
  </div>
</div>
<br>


<div class="row" id="agenda-tabs">


  <ul class="tabs" id="tabs-fixed">

    <li class="tab col s2"><a class="active" href="#item0">全部</a></li>
    <li class="tab col s2"><a href="#item1">运动</a></li>
    <li class="tab col s2"><a href="#item2">娱乐</a></li>
    <li class="tab col s2"><a href="#item3">饭局</a></li>
    <li class="tab col s2"><a href="#item4">旅游</a></li>
    <li class="tab col s2"><a href="#item5">推荐</a></li>
  </ul>

 
    <br>
    <br>
    <br>


  <div id="item0" class="col s12">
    <% @agendas_item = @agendas %>
    <% if @agendas_item.blank?%>
    <% else %>
        <% @agendas_item.each do |agenda| %>
          <% @agenda=agenda %>
          <% @itemid=0%>
            <% if mobile_device? %>
              <%= render 'agdblock'%>
              <br>
            <% else%>
              <%= render 'agdcard'%>
            <% end %>
        <% end %>
    <% end %>
  </div>

  <% @categories.each do |category| %>
    <div id=<%="item"+"#{category.id}"%> class="col s12">
      <% @agendas_item = @agendas.where(category_id: category.id).order(:isoverdue, :datatime)%>
        <% if @agendas_item.blank?%>
        <% else %>
          <% @agendas_item.each do |agenda| %>
            <% @agenda=agenda %>
            <% @itemid=category.id%>
              <% if mobile_device? %>
                <%= render 'agdblock'%>
                <br>
              <% else%>
                <%= render 'agdcard'%>
              <% end %>
          <% end %>
      <% end %>
    </div>
  <% end %>
</div>


<%= render 'layouts/footer' %>